[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip",
  "python310Packages.setuptools",
  "python310Packages.wheel",
  "pango",
  "cairo",
  "gobject-introspection",
  "harfbuzz",
  "gdk-pixbuf",
  "libffi",
  "fontconfig",
  "freetype",
  "libxml2",
  "libxslt"
]

[phases.install]
cmd = "python3 -m venv /opt/venv && . /opt/venv/bin/activate && pip install -e ."

[start]
cmd = "python3 railway-entrypoint.py"
